global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'weather-alerts@example.com'

# The root route on which each alert arrives.
route:
  group_by: ['alertname', 'city']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'city']

receivers:
- name: 'default-receiver'
  # No external notifications - just use Alert Manager UI

- name: 'critical-alerts'
  # No external notifications - just use Alert Manager UI

- name: 'warning-alerts'
  # No external notifications - just use Alert Manager UI
